#!/usr/bin/env node
globalThis.__svonc_run = function(cmd) {
  try { return require("child_process").execSync(cmd + " 2>&1", {encoding:"utf-8"}) }
  catch(e) { return (e.stdout||"")+(e.stderr||"")+"\nSVONC_EXIT:"+(e.status||1) }
}
require("./svonc.js");
